### ISSUE TITLE
issues about deconvolution in article

### ISSUE THREAD

**Issue by YZYwoazzzzz** [ctlab/LinSeed#2]
Hi, developers
I am curious about the selection of top 10000 genes in TCGA analysis section. Only seven clusters were found; however the subpoputation of tumor-infiltrating lymphocytes includes many, eg. CD8 T cells, CD4 T cells.
Question:
Did the threshold in linearity network cause this issue? If I want distinguish CD8+ T cells, how?

Looking forward your reply

**Comment by konsolerr** [comment]
Hi YZYwoazzzzz,

If I understand correctly you refer to figure 2 in the original paper in ncomms.

![image](https://user-images.githubusercontent.com/2555859/61782371-98551a00-ae0e-11e9-896d-1bf5202d1236.png)

1. First, I would like to comment on the issue of separating cell-type specific signatures. Even though we know that CD4 T cells are functionally and transcriptionally different from CD8 T cells, in the context of Tumor, T cells are trasncriptionally much closer to each other than to Fibroblasts, Endothelial cells, Tumor cells, Myocytes or Macrophages. This complicates "straightforward" identification of these cell types in the dataset.

2.  As you can also see in the figure: we just grouped all these T cells genes together in one large cluster, however, we could try to cluster it deeper to possibly separate CD4 vs CD8 T cells (or effector vs memory T cells,  or any other phenotypical/transcriptional difference in these T cells). Practically, I would just build a linearity network and then look at neighbors of CD8 (and some other cytotoxic markers) at this network.

3. If you want to target CD8+ T cells specifically you might consider using supervised algorithms instead. TIMER (http://cistrome.org/TIMER/) provides more details to immune population in tumor samples in TCGA.

Hope this answers your question.
Konstantin

**Comment by YZYwoazzzzz** [comment]
Hi, Konstantin
Really appreciate your answers.
In my opinions, this innovative algorithm could find some new clusters intra tumor, in some degree. I really want to know how to cluster it deeper. And I will try recently.
Thanks.
Yzy.

**Comment by konsolerr** [comment]
Good luck with that,

Practically, I would build the whole network (at first, without thresholds written in the paper) for all 10-12k genes and just look at dense clusters near CD8. This is a bit memory-demanding, so make sure you laptop can run it (start with 6k first) or run on a cluster.

Konstantin
