### ISSUE TITLE
How may we get deconvoluted matrix

### ISSUE THREAD

**Issue by Sharks28** [ctlab/LinSeed#9]
Is there a way to get final deconvoluted expression matrix?  I am looking to extract expression for each cell type for each sample in the data.  I want to import this deconvoluted matrix to the Seurat package and continue analysis.

**Comment by konsolerr** [comment]
Hi, @Sharks28 

Sure, there is a way to do it, if your it is kept in slot "proportions" within your linseed object.
Assume your linseed object called `lo`, then you can get the matrix as

```
lo$proportions
```

Cheers and sorry for the slow reply

**Comment by Sharks28** [comment]
@konsolerr :  thanks for getting back to me.  Your solution would just give me matrix of proportions, right?  I guess what I was going for is complete deconvolution matrix, where we can have expression of genes per cell type.

**Comment by konsolerr** [comment]
@Sharks28 
Sorry, I somehow misread the question, this slot is called signatures
```
lo$signatures
```
